### ISSUE TITLE
Clicar no título "Invariante" ou na Home do meu lateral deveria ir pra Home (hoje está dando refresh no artigo atual)

### ISSUE THREAD

**Issue by brunokoga** [Invariante/invariante#13]
Douglas Fischer [5:08 PM] 

O site do Invariante quando eu clico no titulo ou em Home no menu lateral, não vai pra home.
Volta pro topo do artigo atual.

**Comment by diogot** [comment]
Isso parece resolver
http://downtothewire.io/2015/08/15/configuring-jekyll-for-user-and-project-github-pages/
