### ISSUE TITLE
Criar um fav-icon

### ISSUE THREAD

**Issue by brunokoga** [Invariante/invariante#5]
Precisamos de um fav-icon! Hoje é um "D" nada a ver que veio com o template.

**Comment by diogot** [comment]
Tirei algumas idéias da [wikipedia](https://en.wikipedia.org/wiki/Physical_constant)
- c: velocidade da luz no vácuo
- ħ: constante de Planck/2π
- π: bom e velho pi
- µ
- ƛ
- Ɣ
- δ
- ∂ª

Gosto do ∂ª (é o quadrivetor do gradiente), um belo exemplar de [invariante de Lorentz](https://en.wikipedia.org/wiki/Lorentz_covariance), mas não com essa fonte.

**Comment by talesp** [comment]
Vou fingir que lembro alguma coisa do que aprendi sobre derivadas parciais, gradientes, divergentes, rotacionais e quaternios pra fingir que entendi os paranauê :p

Considerando que em analise de algoritmos uma das coisas estudadas é a invariância de parte do algoritmo durante a prova de sua corretude, podemos usar algo nessa linha :)

**Comment by brunokoga** [comment]
Caraca, seis são muito inteligente. A única palavra quem vem a minha cabeça quando eu penso em "invariante" é: ¯\_(ツ)_/¯

**Comment by brunokoga** [comment]
Boa sorte

**Comment by diogot** [comment]
Coloquei esse ai, commit f0dcd2e9e1e6f13350a7cc0e25d59ff242c0c3a2, beleza?
![apple-touch-icon-144-precomposed](https://cloud.githubusercontent.com/assets/885516/9372880/3be1ed30-46ba-11e5-801c-8e64b70ec3ec.png)
